import { createSlice } from "@reduxjs/toolkit";

const initialState = {
  recipes: [
    {
      recSeq: 1,
      recName: "콩비지동그랑땡",
      recStep: null,
      recCost: null,
      recCode: "195453",
      recSummary: "두부대신 콩비지를 넣어 만든 동그랑땡 맛도 좋아요!",
      cateCode: "3020001",
      cateFrac: "한식",
      foodCode: "3010018",
      foodFrac: "부침",
      cookingTime: "30분",
      recCalorie: "0Kcal",
      recAmount: "3인분",
      recLevel: "보통",
      recIngFrac: " ",
      recPrice: 1000,
      recImg: "http://file.okdab.com/recipe/148299577268400131.jpg",
      reviews: [],
      recipeIngredientList: [
        {
          recIngSeq: 5327,
          recName: "콩비지동그랑땡",
          ingName: "계란",
          ingAmount: "5개",
          ingType: "주재료",
        },
        {
          recIngSeq: 5328,
          recName: "콩비지동그랑땡",
          ingName: "다진마늘",
          ingAmount: "1T",
          ingType: "주재료",
        },
        {
          recIngSeq: 5329,
          recName: "콩비지동그랑땡",
          ingName: "다짐육",
          ingAmount: "200g",
          ingType: "주재료",
        },
        {
          recIngSeq: 5330,
          recName: "콩비지동그랑땡",
          ingName: "대파",
          ingAmount: "1대",
          ingType: "주재료",
        },
        {
          recIngSeq: 5331,
          recName: "콩비지동그랑땡",
          ingName: "밀가루",
          ingAmount: "2CUP",
          ingType: "주재료",
        },
        {
          recIngSeq: 5332,
          recName: "콩비지동그랑땡",
          ingName: "배추",
          ingAmount: "2잎",
          ingType: "주재료",
        },
        {
          recIngSeq: 5333,
          recName: "콩비지동그랑땡",
          ingName: "부침가루",
          ingAmount: "1/2T",
          ingType: "주재료",
        },
        {
          recIngSeq: 5334,
          recName: "콩비지동그랑땡",
          ingName: "소금",
          ingAmount: "2t",
          ingType: "주재료",
        },
        {
          recIngSeq: 5335,
          recName: "콩비지동그랑땡",
          ingName: "전분",
          ingAmount: "1/2T",
          ingType: "주재료",
        },
        {
          recIngSeq: 5336,
          recName: "콩비지동그랑땡",
          ingName: "참기름",
          ingAmount: "1T",
          ingType: "주재료",
        },
        {
          recIngSeq: 5337,
          recName: "콩비지동그랑땡",
          ingName: "콩비지",
          ingAmount: "300g",
          ingType: "주재료",
        },
        {
          recIngSeq: 5338,
          recName: "콩비지동그랑땡",
          ingName: "호박",
          ingAmount: "1/2개",
          ingType: "주재료",
        },
        {
          recIngSeq: 5339,
          recName: "콩비지동그랑땡",
          ingName: "후추",
          ingAmount: "1/2t",
          ingType: "주재료",
        },
      ],
      recipeProcessList: [
        {
          recProSeq: 1,
          recCode: "195453",
          recOrder: "5",
          recDes:
            "모양을 낸 반죽에 밀가루를 묻히고, 계란을 푼 계란물을 묻혀준다.",
          proUrl: "http://file.okdab.com/recipe/148299577271000135.jpg",
          proTip: " ",
        },
        {
          recProSeq: 2,
          recCode: "195453",
          recOrder: "4",
          recDes: "동그랑땡 반죽을 동글납작하게 모양을 잡아준다.",
          proUrl: "http://file.okdab.com/recipe/148299577270600134.jpg",
          proTip: " ",
        },
        {
          recProSeq: 3,
          recCode: "195453",
          recOrder: "3",
          recDes:
            "부침가루와 전분을 넣고 계란 1개를 넣어 반죽하듯 잘 섞어준다.",
          proUrl: "http://file.okdab.com/recipe/148299577270200133.jpg",
          proTip: " ",
        },
        {
          recProSeq: 4,
          recCode: "195453",
          recOrder: "2",
          recDes:
            "볼에 콩비지와 고기, 다진 채소, 다진마늘, 후추, 소금, 참기름을 넣어준다.",
          proUrl: "http://file.okdab.com/recipe/148299577269600132.jpg",
          proTip: " ",
        },
        {
          recProSeq: 5,
          recCode: "195453",
          recOrder: "1",
          recDes: "대파, 호박, 배추는 작게 다져준다.",
          proUrl: " ",
          proTip: " ",
        },
        {
          recProSeq: 6,
          recCode: "195453",
          recOrder: "6",
          recDes:
            "달궈진 팬에 기름을 두르고 옷을 계란물옷을 입힌 동그랑땡을 노릇하게 익혀준다.",
          proUrl: "http://file.okdab.com/recipe/148299577271500136.jpg",
          proTip: " ",
        },
      ],
    },
    {
      recSeq: 2,
      recName: "누드김밥",
      recStep: null,
      recCost: null,
      recCode: "195428",
      recSummary:
        "건강한 재료로 가득담아 말은 누드김밥! 고기가 없어도 맛있어요!!",
      cateCode: "3020009",
      cateFrac: "퓨전",
      foodCode: "3010001",
      foodFrac: "밥",
      cookingTime: "20분",
      recCalorie: "0Kcal",
      recAmount: "3인분",
      recLevel: "보통",
      recIngFrac: " ",
      recPrice: 2000,
      recImg: "http://file.okdab.com/recipe/148299332505800120.jpg",
      reviews: [],
      recipeIngredientList: [
        {
          recIngSeq: 1242,
          recName: "누드김밥",
          ingName: "가지",
          ingAmount: "1/2개",
          ingType: "주재료",
        },
        {
          recIngSeq: 1243,
          recName: "누드김밥",
          ingName: "김밥용김",
          ingAmount: "2장",
          ingType: "주재료",
        },
        {
          recIngSeq: 1244,
          recName: "누드김밥",
          ingName: "당근",
          ingAmount: "1/2개",
          ingType: "주재료",
        },
        {
          recIngSeq: 1245,
          recName: "누드김밥",
          ingName: "두부",
          ingAmount: "2.5T",
          ingType: "양념",
        },
        {
          recIngSeq: 1246,
          recName: "누드김밥",
          ingName: "마요네즈",
          ingAmount: "1T",
          ingType: "양념",
        },
        {
          recIngSeq: 1247,
          recName: "누드김밥",
          ingName: "밥",
          ingAmount: "3공기",
          ingType: "주재료",
        },
        {
          recIngSeq: 1248,
          recName: "누드김밥",
          ingName: "설탕",
          ingAmount: "0.5T",
          ingType: "양념",
        },
        {
          recIngSeq: 1249,
          recName: "누드김밥",
          ingName: "소금",
          ingAmount: "약간",
          ingType: "주재료",
        },
        {
          recIngSeq: 1250,
          recName: "누드김밥",
          ingName: "식초",
          ingAmount: "0.5T",
          ingType: "양념",
        },
        {
          recIngSeq: 1251,
          recName: "누드김밥",
          ingName: "어린잎채소",
          ingAmount: "약간",
          ingType: "주재료",
        },
        {
          recIngSeq: 1252,
          recName: "누드김밥",
          ingName: "오이",
          ingAmount: "1/2개",
          ingType: "주재료",
        },
        {
          recIngSeq: 1253,
          recName: "누드김밥",
          ingName: "참기름",
          ingAmount: "약간",
          ingType: "주재료",
        },
        {
          recIngSeq: 1254,
          recName: "누드김밥",
          ingName: "통깨",
          ingAmount: "0.5T",
          ingType: "양념",
        },
        {
          recIngSeq: 1255,
          recName: "누드김밥",
          ingName: "통깨",
          ingAmount: "약간",
          ingType: "주재료",
        },
      ],
      recipeProcessList: [
        {
          recProSeq: 7,
          recCode: "195428",
          recOrder: "8",
          recDes: "접시에 어린잎 채소를 깔아주고 그 위에 자른 김밥을 올려준다.",
          proUrl: "http://file.okdab.com/recipe/148299332509200128.jpg",
          proTip: " ",
        },
        {
          recProSeq: 8,
          recCode: "195428",
          recOrder: "9",
          recDes:
            "믹서기에 두부, 식초, 설탕, 마요네즈, 통깨를 넣고 갈아 두부드레싱을 만들어 준다.",
          proUrl: "http://file.okdab.com/recipe/148299332509700129.jpg",
          proTip: " ",
        },
        {
          recProSeq: 9,
          recCode: "195428",
          recOrder: "10",
          recDes: "접시에 담긴 김밥위에 두부 드레싱을 뿌려준다.",
          proUrl: "http://file.okdab.com/recipe/148299332510100130.jpg",
          proTip: " ",
        },
        {
          recProSeq: 10,
          recCode: "195428",
          recOrder: "7",
          recDes:
            "완성된 김밥위에 참기름과 통깨를 발라 먹기 좋은 크기로 잘라준다.",
          proUrl: "http://file.okdab.com/recipe/148299332508800127.jpg",
          proTip: " ",
        },
        {
          recProSeq: 11,
          recCode: "195428",
          recOrder: "6",
          recDes: "김발과 랩을 빼 주며 김밥을 말아 준다.",
          proUrl: "http://file.okdab.com/recipe/148299332508400126.jpg",
          proTip: " ",
        },
        {
          recProSeq: 12,
          recCode: "195428",
          recOrder: "5",
          recDes: "뒤집은 김위에 김밥속 재료인 당근, 가지, 오이를 올려준다.",
          proUrl: "http://file.okdab.com/recipe/148299332508000125.jpg",
          proTip: " ",
        },
        {
          recProSeq: 13,
          recCode: "195428",
          recOrder: "4",
          recDes:
            "김말이 위에 랩을 깔아주고 김을 올려놓고 밥을 김 위에 잘 펴 뒤집어 준다.",
          proUrl: "http://file.okdab.com/recipe/148299332507500124.jpg",
          proTip: " ",
        },
        {
          recProSeq: 14,
          recCode: "195428",
          recOrder: "3",
          recDes: "밥에 통깨와 참기름  맛소금을 넣고 주걱을 세워 섞어준다.",
          proUrl: "http://file.okdab.com/recipe/148299332507100123.jpg",
          proTip: " ",
        },
        {
          recProSeq: 15,
          recCode: "195428",
          recOrder: "1",
          recDes: "당근과 오이는 얇게 슬라이스 해준다.\n가지는 길게 잘라준다.",
          proUrl: "http://file.okdab.com/recipe/148299332506300121.jpg",
          proTip: " ",
        },
        {
          recProSeq: 16,
          recCode: "195428",
          recOrder: "2",
          recDes: "오이를 제외한 당근과 가지를 기름 두른 팬에 볶아준다.",
          proUrl: "http://file.okdab.com/recipe/148299332506700122.jpg",
          proTip: "가지는 간장으로 당근은 소금으로 간을 해준다.",
        },
      ],
    },
    {
      recSeq: 3,
      recName: "쪽파 새우강회",
      recStep: null,
      recCost: null,
      recCode: "180363",
      recSummary:
        "새우에 쪽파를 감아 간단하게 만들지만 새우와 쪽파의 달콤한 맛과 새콤한 초고추장의 환상의 콤비! 거기에 건강까지 좋은 영양만점 쪽파 새우강회!!",
      cateCode: "3020009",
      cateFrac: "퓨전",
      foodCode: "3010007",
      foodFrac: "나물/생채/샐러드",
      cookingTime: "20분",
      recCalorie: "0Kcal",
      recAmount: "2인분",
      recLevel: "초보환영",
      recIngFrac: " ",
      recPrice: 3000,
      recImg: "http://file.okdab.com/recipe/148299002655300119.jpg",
      reviews: [],
      recipeIngredientList: [
        {
          recIngSeq: 4860,
          recName: "쪽파 새우강회",
          ingName: "고추장",
          ingAmount: "2T",
          ingType: "양념",
        },
        {
          recIngSeq: 4861,
          recName: "쪽파 새우강회",
          ingName: "설탕",
          ingAmount: "1+1/2T",
          ingType: "양념",
        },
        {
          recIngSeq: 4862,
          recName: "쪽파 새우강회",
          ingName: "소금",
          ingAmount: "약간",
          ingType: "주재료",
        },
        {
          recIngSeq: 4863,
          recName: "쪽파 새우강회",
          ingName: "식초",
          ingAmount: "2T",
          ingType: "양념",
        },
        {
          recIngSeq: 4864,
          recName: "쪽파 새우강회",
          ingName: "중새우",
          ingAmount: "15마리",
          ingType: "주재료",
        },
        {
          recIngSeq: 4865,
          recName: "쪽파 새우강회",
          ingName: "쪽파",
          ingAmount: "15대",
          ingType: "주재료",
        },
        {
          recIngSeq: 4866,
          recName: "쪽파 새우강회",
          ingName: "통깨",
          ingAmount: "약간",
          ingType: "양념",
        },
      ],
      recipeProcessList: [
        {
          recProSeq: 17,
          recCode: "180363",
          recOrder: "5",
          recDes: "새우에 쪽파를 감아 접시에 담아 준다.",
          proUrl: "http://file.okdab.com/recipe/148298988812700118.jpg",
          proTip: " ",
        },
        {
          recProSeq: 18,
          recCode: "180363",
          recOrder: "3",
          recDes: "새우는 끓는 물에 소금을 약간 넣고 데친다.",
          proUrl: " ",
          proTip: " ",
        },
        {
          recProSeq: 19,
          recCode: "180363",
          recOrder: "2",
          recDes:
            "쪽파는 끓는 물에 소금을 넣고 살짝 데친 후 찬물에 담갔다 물기를 빼준다.",
          proUrl: "http://file.okdab.com/recipe/148298988812000116.jpg",
          proTip: " ",
        },
        {
          recProSeq: 20,
          recCode: "180363",
          recOrder: "1",
          recDes: "새우와 쪽파는 데치기 전에 깨끗하게 손질한다.",
          proUrl: "http://file.okdab.com/recipe/148298988811400115.jpg",
          proTip: " ",
        },
        {
          recProSeq: 21,
          recCode: "180363",
          recOrder: "4",
          recDes:
            "그릇에 고추장, 식초, 설탕, 깨를 넣고 잘 섞어 초장을 만들어 준다.",
          proUrl: "http://file.okdab.com/recipe/148298988812300117.jpg",
          proTip: " ",
        },
      ],
    },
    {
      recSeq: 4,
      recName: "카레토마토달걀볶음밥",
      recStep: null,
      recCost: null,
      recCode: "180344",
      recSummary:
        "토마토와 달걀을 넣은 볶음밥에 카레소스를 두른 영양만점 볶음밥",
      cateCode: "3020009",
      cateFrac: "퓨전",
      foodCode: "3010001",
      foodFrac: "밥",
      cookingTime: "30분",
      recCalorie: "0Kcal",
      recAmount: "1인분",
      recLevel: "초보환영",
      recIngFrac: " ",
      recPrice: 4000,
      recImg: "http://file.okdab.com/recipe/148291443772500013.jpg",
      reviews: [],
      recipeIngredientList: [
        {
          recIngSeq: 5177,
          recName: "카레토마토달걀볶음밥",
          ingName: "달걀",
          ingAmount: "2개",
          ingType: "주재료",
        },
        {
          recIngSeq: 5178,
          recName: "카레토마토달걀볶음밥",
          ingName: "물",
          ingAmount: "280ml",
          ingType: "부재료",
        },
        {
          recIngSeq: 5179,
          recName: "카레토마토달걀볶음밥",
          ingName: "밥",
          ingAmount: "1공기",
          ingType: "주재료",
        },
        {
          recIngSeq: 5180,
          recName: "카레토마토달걀볶음밥",
          ingName: "방울토마토",
          ingAmount: "15알",
          ingType: "주재료",
        },
        {
          recIngSeq: 5181,
          recName: "카레토마토달걀볶음밥",
          ingName: "셀러리",
          ingAmount: "1대",
          ingType: "주재료",
        },
        {
          recIngSeq: 5182,
          recName: "카레토마토달걀볶음밥",
          ingName: "양파",
          ingAmount: "1/8개",
          ingType: "주재료",
        },
        {
          recIngSeq: 5183,
          recName: "카레토마토달걀볶음밥",
          ingName: "카레가루",
          ingAmount: "3T",
          ingType: "부재료",
        },
        {
          recIngSeq: 5184,
          recName: "카레토마토달걀볶음밥",
          ingName: "햄",
          ingAmount: "50g",
          ingType: "주재료",
        },
        {
          recIngSeq: 5185,
          recName: "카레토마토달걀볶음밥",
          ingName: "후추",
          ingAmount: "약간",
          ingType: "주재료",
        },
      ],
      recipeProcessList: [
        {
          recProSeq: 22,
          recCode: "180344",
          recOrder: "4",
          recDes:
            "달궈진 팬에 올리브유를 두르고 양파, 셀러리, 토마토 순서대로 볶아준다.",
          proUrl: "http://file.okdab.com/recipe/148291443776100016.jpg",
          proTip: " ",
        },
        {
          recProSeq: 23,
          recCode: "180344",
          recOrder: "9",
          recDes: "그릇에 볶음밥과 카레소스를 함께 담는다.",
          proUrl: "http://file.okdab.com/recipe/148291443779700021.jpg",
          proTip: " ",
        },
        {
          recProSeq: 24,
          recCode: "180344",
          recOrder: "8",
          recDes: "냄비에 물과 카레가루를 넣고 끓여 카레소스를 만들어 준다.",
          proUrl: "http://file.okdab.com/recipe/148291443779100020.jpg",
          proTip: " ",
        },
        {
          recProSeq: 25,
          recCode: "180344",
          recOrder: "7",
          recDes: "만들어진 스크램블에그를 볶음밥과 잘 섞어준다.",
          proUrl: "http://file.okdab.com/recipe/148291443778100019.jpg",
          proTip: " ",
        },
        {
          recProSeq: 26,
          recCode: "180344",
          recOrder: "6",
          recDes:
            "볶아진 밥을 한쪽으로 몰아놓고 풀어놓은 달걀을 팬에 부어 스크램블에그를 만든다.",
          proUrl: "http://file.okdab.com/recipe/148291443777600018.jpg",
          proTip: " ",
        },
        {
          recProSeq: 27,
          recCode: "180344",
          recOrder: "1",
          recDes: "볶음밥에 들어갈 양파와, 셀러리, 햄을 다져서 준비한다.",
          proUrl: "http://file.okdab.com/recipe/148291443773800014.jpg",
          proTip: " ",
        },
        {
          recProSeq: 28,
          recCode: "180344",
          recOrder: "2",
          recDes: "계란은 볼에 풀어준다.",
          proUrl: " ",
          proTip: " ",
        },
        {
          recProSeq: 29,
          recCode: "180344",
          recOrder: "3",
          recDes:
            "방울토마토는 칼집을 내어 끓는 물을 부었다가 건져 껍질을 제거한다.",
          proUrl: "http://file.okdab.com/recipe/148291443775600015.jpg",
          proTip: " ",
        },
        {
          recProSeq: 30,
          recCode: "180344",
          recOrder: "5",
          recDes: "볶아진 재료에 밥을 넣고 후추를 뿌려 볶아준다.",
          proUrl: "http://file.okdab.com/recipe/148291443777100017.jpg",
          proTip: " ",
        },
      ],
    },
    {
      recSeq: 5,
      recName: "식빵고구마파이",
      recStep: null,
      recCost: null,
      recCode: "180330",
      recSummary: "식빵을 이용한 간단 고구마파이! 아이들 영양 간식으로 딱!",
      cateCode: "3020002",
      cateFrac: "서양",
      foodCode: "3010014",
      foodFrac: "빵/과자",
      cookingTime: "30분",
      recCalorie: "0Kcal",
      recAmount: "2인분",
      recLevel: "초보환영",
      recIngFrac: " ",
      recPrice: 5000,
      recImg: "http://file.okdab.com/recipe/148291043686100008.jpg",
      reviews: [],
      recipeIngredientList: [
        {
          recIngSeq: 3612,
          recName: "식빵고구마파이",
          ingName: "건블루베리",
          ingAmount: "1/2T",
          ingType: "주재료",
        },
        {
          recIngSeq: 3613,
          recName: "식빵고구마파이",
          ingName: "고구마",
          ingAmount: "2개(大)",
          ingType: "주재료",
        },
        {
          recIngSeq: 3614,
          recName: "식빵고구마파이",
          ingName: "꿀",
          ingAmount: "1/2T",
          ingType: "주재료",
        },
        {
          recIngSeq: 3615,
          recName: "식빵고구마파이",
          ingName: "달걀노른자",
          ingAmount: "1개",
          ingType: "주재료",
        },
        {
          recIngSeq: 3616,
          recName: "식빵고구마파이",
          ingName: "마요네즈",
          ingAmount: "1T",
          ingType: "주재료",
        },
        {
          recIngSeq: 3617,
          recName: "식빵고구마파이",
          ingName: "소금",
          ingAmount: "약간",
          ingType: "주재료",
        },
        {
          recIngSeq: 3618,
          recName: "식빵고구마파이",
          ingName: "식빵",
          ingAmount: "5쪽",
          ingType: "주재료",
        },
        {
          recIngSeq: 3619,
          recName: "식빵고구마파이",
          ingName: "우유",
          ingAmount: "1cup",
          ingType: "주재료",
        },
      ],
      recipeProcessList: [
        {
          recProSeq: 31,
          recCode: "180330",
          recOrder: "4",
          recDes:
            "식빵을 반으로 접고 고구마메시가 튀어나오지 않도록 빵 가장자리를 포크를 이용해 꾸욱~눌러준다.",
          proUrl: " ",
          proTip: " ",
        },
        {
          recProSeq: 32,
          recCode: "180330",
          recOrder: "3",
          recDes:
            "식빵을 밀대로 얇게 밀어 납작하게 만들어 준 후 가장자리는 깔끔하게 잘라 낸다.\n식빵의 가장자리에 달걀물을 바르고 고구마메시를 식빵위에 올려준다.",
          proUrl: "http://file.okdab.com/recipe/148291043688000011.jpg",
          proTip: " ",
        },
        {
          recProSeq: 33,
          recCode: "180330",
          recOrder: "1",
          recDes: "깨끗하게 씻은 고구마를 찜통에 넣고 쪄준다.",
          proUrl: "http://file.okdab.com/recipe/148291043686500009.jpg",
          proTip: " ",
        },
        {
          recProSeq: 34,
          recCode: "180330",
          recOrder: "2",
          recDes:
            "잘 쪄진 고구마는 껍질을 벗기고 볼에 담에 으깨고 마요네즈, 우유, 건블루베리, 꿀, 소금을 넣고 으깬 고구마와 잘 섞어 고구마메시를 만들어 준다.",
          proUrl: "http://file.okdab.com/recipe/148291043686800010.jpg",
          proTip: " ",
        },
        {
          recProSeq: 35,
          recCode: "180330",
          recOrder: "5",
          recDes:
            "사선으로 빵에 칼집을 내어 빵 겉에 달걀물을 고루 발라준다.\n200도로 예열된 오븐에 약 6분간 구워준다.",
          proUrl: "http://file.okdab.com/recipe/148291043690000012.jpg",
          proTip: " ",
        },
      ],
    },
    {
      recSeq: 6,
      recName: "배추만두",
      recStep: null,
      recCost: null,
      recCode: "120476",
      recSummary:
        "배추로 만든 깜찍한 배추주머니 만두! 아삭한 배추와 영양으로 가~득 채운 보기도 좋고 맛도 좋은 배추만두랍니다.",
      cateCode: "3020001",
      cateFrac: "한식",
      foodCode: "3010006",
      foodFrac: "찜",
      cookingTime: "30분",
      recCalorie: "0Kcal",
      recAmount: "2인분",
      recLevel: "보통",
      recIngFrac: " ",
      recPrice: 6000,
      recImg: "http://file.okdab.com/recipe/148230648948900343.jpg",
      reviews: [],
      recipeIngredientList: [
        {
          recIngSeq: 2498,
          recName: "배추만두",
          ingName: "간장",
          ingAmount: "1T",
          ingType: "양념",
        },
        {
          recIngSeq: 2499,
          recName: "배추만두",
          ingName: "다진마늘",
          ingAmount: "1/2T",
          ingType: "부재료",
        },
        {
          recIngSeq: 2500,
          recName: "배추만두",
          ingName: "다진생강",
          ingAmount: "2t",
          ingType: "부재료",
        },
        {
          recIngSeq: 2501,
          recName: "배추만두",
          ingName: "다짐육(돼지고기)",
          ingAmount: "100g",
          ingType: "부재료",
        },
        {
          recIngSeq: 2502,
          recName: "배추만두",
          ingName: "다짐육(소고기)",
          ingAmount: "100g",
          ingType: "부재료",
        },
        {
          recIngSeq: 2503,
          recName: "배추만두",
          ingName: "달걀",
          ingAmount: "1개",
          ingType: "부재료",
        },
        {
          recIngSeq: 2504,
          recName: "배추만두",
          ingName: "당근",
          ingAmount: "1/6개",
          ingType: "부재료",
        },
        {
          recIngSeq: 2505,
          recName: "배추만두",
          ingName: "당면",
          ingAmount: "한줌",
          ingType: "부재료",
        },
        {
          recIngSeq: 2506,
          recName: "배추만두",
          ingName: "두부",
          ingAmount: "1/2모",
          ingType: "부재료",
        },
        {
          recIngSeq: 2507,
          recName: "배추만두",
          ingName: "들기름",
          ingAmount: "1T",
          ingType: "양념",
        },
        {
          recIngSeq: 2508,
          recName: "배추만두",
          ingName: "미나리",
          ingAmount: "10줄기",
          ingType: "주재료",
        },
        {
          recIngSeq: 2509,
          recName: "배추만두",
          ingName: "배추잎",
          ingAmount: "10장",
          ingType: "주재료",
        },
        {
          recIngSeq: 2510,
          recName: "배추만두",
          ingName: "버섯",
          ingAmount: "4개",
          ingType: "부재료",
        },
        {
          recIngSeq: 2511,
          recName: "배추만두",
          ingName: "소금",
          ingAmount: "3t",
          ingType: "양념",
        },
        {
          recIngSeq: 2512,
          recName: "배추만두",
          ingName: "통깨",
          ingAmount: "약간",
          ingType: "양념",
        },
        {
          recIngSeq: 2513,
          recName: "배추만두",
          ingName: "후추",
          ingAmount: "약간",
          ingType: "양념",
        },
      ],
      recipeProcessList: [
        {
          recProSeq: 36,
          recCode: "120476",
          recOrder: "8",
          recDes:
            "데친 배추잎을 펼치고 가운데 만두소를 넣고 복주머니 형태로 감싼 뒤 미나리로 묶어준다.",
          proUrl: "http://file.okdab.com/recipe/148230648951600351.jpg",
          proTip: " ",
        },
        {
          recProSeq: 37,
          recCode: "120476",
          recOrder: "2",
          recDes:
            "다짐육은 키친타올로 살짝 눌러 핏물을 제거하고, 두부는 물기를 빼준다.",
          proUrl: "http://file.okdab.com/recipe/148230648949700345.jpg",
          proTip: " ",
        },
        {
          recProSeq: 38,
          recCode: "120476",
          recOrder: "6",
          recDes: "배추만두를 묶을 미나리를 소금물에 살짝 데쳐준다.",
          proUrl: "http://file.okdab.com/recipe/148230648951000349.jpg",
          proTip: "미나리를 오래 데치면 질겨진다.",
        },
        {
          recProSeq: 39,
          recCode: "120476",
          recOrder: "5",
          recDes: "대를 제거한 배추잎을 찜통에 넣고 살짝 쪄준다.",
          proUrl: "http://file.okdab.com/recipe/148230648950600348.jpg",
          proTip: "오래 찌면 배추의 아삭함이 없어진다.",
        },
        {
          recProSeq: 40,
          recCode: "120476",
          recOrder: "4",
          recDes: "만두의 피가 될 배추는 잎 부분을 뺀 하얀 대 부분을 잘라준다.",
          proUrl: "http://file.okdab.com/recipe/148230648950300347.jpg",
          proTip: " ",
        },
        {
          recProSeq: 41,
          recCode: "120476",
          recOrder: "3",
          recDes: "큰 볼에 준비한 만두소 재료를 넣고 잘 섞어 준다.",
          proUrl: "http://file.okdab.com/recipe/148230648950000346.jpg",
          proTip: " ",
        },
        {
          recProSeq: 42,
          recCode: "120476",
          recOrder: "10",
          recDes: "찜통에 배추만두를 넣고 5분간 쪄준다.",
          proUrl: "http://file.okdab.com/recipe/148230648952900353.jpg",
          proTip: " ",
        },
        {
          recProSeq: 43,
          recCode: "120476",
          recOrder: "9",
          recDes:
            "복주머니 형태가 어려우면 막대 형태로 말아 미나리로 묶어준다.",
          proUrl: "http://file.okdab.com/recipe/148230648952700352.jpg",
          proTip: " ",
        },
        {
          recProSeq: 44,
          recCode: "120476",
          recOrder: "7",
          recDes: "만두소는 고기가 익을 때 까지 볶아준다.",
          proUrl: "http://file.okdab.com/recipe/148230648951300350.jpg",
          proTip: " ",
        },
        {
          recProSeq: 45,
          recCode: "120476",
          recOrder: "1",
          recDes:
            "채소들은 깨끗하게 씻어 물기를 빼준 후 만두소에 들어갈 재료는 잘게 다져 준비한다.",
          proUrl: "http://file.okdab.com/recipe/148230648949400344.jpg",
          proTip: "배추잎은 큰 것으로 준비한다.",
        },
      ],
    },
    {
      recSeq: 7,
      recName: "당근잎 감자전",
      recStep: null,
      recCost: null,
      recCode: "120463",
      recSummary: "당근 향이 나는 향긋한 당근잎 감자전",
      cateCode: "3020001",
      cateFrac: "한식",
      foodCode: "3010018",
      foodFrac: "부침",
      cookingTime: "20분",
      recCalorie: "0Kcal",
      recAmount: "2인분",
      recLevel: "보통",
      recIngFrac: " ",
      recPrice: 7000,
      recImg: "http://file.okdab.com/recipe/148229812483500337.jpg",
      reviews: [
        {
          recRevSeq: 1,
          recRevTitle: "user test",
          recRevContent: "test1",
          recRevGrade: 4,
          recRevRegUser: null,
          revRegDate: "2022-09-23T01:48:57.925383",
          revModDate: "2022-09-23T01:48:57.925383",
        },
        {
          recRevSeq: 2,
          recRevTitle: "user test2",
          recRevContent: "test1",
          recRevGrade: 4,
          recRevRegUser: null,
          revRegDate: "2022-09-23T02:21:02.393372",
          revModDate: "2022-09-23T02:21:02.393372",
        },
        {
          recRevSeq: 3,
          recRevTitle: "user test3",
          recRevContent: "test1",
          recRevGrade: 4,
          recRevRegUser: null,
          revRegDate: "2022-09-23T02:38:50.917654",
          revModDate: "2022-09-23T02:38:50.917654",
        },
        {
          recRevSeq: 4,
          recRevTitle: "user test4",
          recRevContent: "test1",
          recRevGrade: 4,
          recRevRegUser: null,
          revRegDate: "2022-09-23T02:40:29.290518",
          revModDate: "2022-09-23T02:40:29.290518",
        },
        {
          recRevSeq: 5,
          recRevTitle: "user test5",
          recRevContent: "test1",
          recRevGrade: 4,
          recRevRegUser: null,
          revRegDate: "2022-09-23T05:19:24.382988",
          revModDate: "2022-09-23T05:19:24.382988",
        },
      ],
      recipeIngredientList: [
        {
          recIngSeq: 1521,
          recName: "당근잎 감자전",
          ingName: "감자",
          ingAmount: "2개",
          ingType: "주재료",
        },
        {
          recIngSeq: 1522,
          recName: "당근잎 감자전",
          ingName: "당근잎",
          ingAmount: "약간",
          ingType: "주재료",
        },
        {
          recIngSeq: 1523,
          recName: "당근잎 감자전",
          ingName: "당근채",
          ingAmount: "약간",
          ingType: "주재료",
        },
        {
          recIngSeq: 1524,
          recName: "당근잎 감자전",
          ingName: "부침가루",
          ingAmount: "6T",
          ingType: "주재료",
        },
        {
          recIngSeq: 1525,
          recName: "당근잎 감자전",
          ingName: "소금",
          ingAmount: "약간",
          ingType: "주재료",
        },
        {
          recIngSeq: 1526,
          recName: "당근잎 감자전",
          ingName: "양파",
          ingAmount: "1/3개",
          ingType: "주재료",
        },
      ],
      recipeProcessList: [
        {
          recProSeq: 46,
          recCode: "120463",
          recOrder: "6",
          recDes: "앞뒤로 뒤집으며 잘 익혀준다.",
          proUrl: " ",
          proTip: " ",
        },
        {
          recProSeq: 47,
          recCode: "120463",
          recOrder: "2",
          recDes:
            "볼에 강판에 간 감자와 다진 양파를 넣고 소금을 살짝 넣어준다.",
          proUrl: "http://file.okdab.com/recipe/148229812484300339.jpg",
          proTip: " ",
        },
        {
          recProSeq: 48,
          recCode: "120463",
          recOrder: "1",
          recDes: "껍질을 벗긴 감자를 강판에 간다.",
          proUrl: "http://file.okdab.com/recipe/148229812484000338.jpg",
          proTip: " ",
        },
        {
          recProSeq: 49,
          recCode: "120463",
          recOrder: "4",
          recDes: "당근 잎은 큰 줄기는 때어내어 깨끗하게 손질한다.",
          proUrl: "http://file.okdab.com/recipe/148229812484900341.jpg",
          proTip: "당근잎의 줄기는 뻣뻣하고 질기므로 식감이 좋지 않다.",
        },
        {
          recProSeq: 50,
          recCode: "120463",
          recOrder: "5",
          recDes:
            "중불로 달군 팬에 감자전 반죽을 넓게 펼친 다음 당근잎과 당근채를  반죽위에 올려 모양을 낸다.",
          proUrl: "http://file.okdab.com/recipe/148229812485200342.jpg",
          proTip: "당근과 당근 잎을 잘게 다진 후 반죽과 함께 섞어 붙여도 좋다.",
        },
        {
          recProSeq: 51,
          recCode: "120463",
          recOrder: "3",
          recDes: "볼에 부침가루를 농도에 맞게 넣어 준다.",
          proUrl: "http://file.okdab.com/recipe/148229812484600340.jpg",
          proTip:
            "감자에서 물이 나오기 때문에 따로 물을 넣지 않아도 되지만 농도에 맞게 물과 부침가루를 첨가한다.",
        },
      ],
    },
    {
      recSeq: 8,
      recName: "단호박 고등어조림",
      recStep: null,
      recCost: null,
      recCode: "120441",
      recSummary: "달콤한 단호박으로 만든 달콤 짭짜름한 고등어조림",
      cateCode: "3020001",
      cateFrac: "한식",
      foodCode: "3010003",
      foodFrac: "조림",
      cookingTime: "30분",
      recCalorie: "0Kcal",
      recAmount: "4인분",
      recLevel: "보통",
      recIngFrac: " ",
      recPrice: 8000,
      recImg: "http://file.okdab.com/recipe/148222411418400027.jpg",
      reviews: [],
      recipeIngredientList: [
        {
          recIngSeq: 1305,
          recName: "단호박 고등어조림",
          ingName: "간장",
          ingAmount: "1T",
          ingType: "양념",
        },
        {
          recIngSeq: 1306,
          recName: "단호박 고등어조림",
          ingName: "고등어",
          ingAmount: "2마리",
          ingType: "주재료",
        },
        {
          recIngSeq: 1307,
          recName: "단호박 고등어조림",
          ingName: "고추장",
          ingAmount: "1T",
          ingType: "부재료",
        },
        {
          recIngSeq: 1308,
          recName: "단호박 고등어조림",
          ingName: "고춧가루",
          ingAmount: "2T",
          ingType: "양념",
        },
        {
          recIngSeq: 1309,
          recName: "단호박 고등어조림",
          ingName: "다진마늘",
          ingAmount: "2T",
          ingType: "양념",
        },
        {
          recIngSeq: 1310,
          recName: "단호박 고등어조림",
          ingName: "단호박",
          ingAmount: "1개",
          ingType: "주재료",
        },
        {
          recIngSeq: 1311,
          recName: "단호박 고등어조림",
          ingName: "된장",
          ingAmount: "1T",
          ingType: "부재료",
        },
        {
          recIngSeq: 1312,
          recName: "단호박 고등어조림",
          ingName: "들기름",
          ingAmount: "1T",
          ingType: "양념",
        },
        {
          recIngSeq: 1313,
          recName: "단호박 고등어조림",
          ingName: "무",
          ingAmount: "1/3개",
          ingType: "주재료",
        },
        {
          recIngSeq: 1314,
          recName: "단호박 고등어조림",
          ingName: "설탕",
          ingAmount: "1/2T",
          ingType: "양념",
        },
        {
          recIngSeq: 1315,
          recName: "단호박 고등어조림",
          ingName: "쌀뜨물",
          ingAmount: "4컵",
          ingType: "주재료",
        },
        {
          recIngSeq: 1316,
          recName: "단호박 고등어조림",
          ingName: "양파",
          ingAmount: "1/2개",
          ingType: "주재료",
        },
        {
          recIngSeq: 1317,
          recName: "단호박 고등어조림",
          ingName: "청양고추",
          ingAmount: "2개",
          ingType: "주재료",
        },
        {
          recIngSeq: 1318,
          recName: "단호박 고등어조림",
          ingName: "홍고추",
          ingAmount: "1개",
          ingType: "주재료",
        },
      ],
      recipeProcessList: [
        {
          recProSeq: 52,
          recCode: "120441",
          recOrder: "2",
          recDes: "냄비에 쌀뜨물은 붓고  육수재료와 무를 넣고 끓여준다.",
          proUrl: "http://file.okdab.com/recipe/148222411419300029.jpg",
          proTip: " ",
        },
        {
          recProSeq: 53,
          recCode: "120441",
          recOrder: "5",
          recDes: "고등어가 살짝 익으면 단고구마와 양파를 넣어준다.",
          proUrl: "http://file.okdab.com/recipe/148222411420400032.jpg",
          proTip: " ",
        },
        {
          recProSeq: 54,
          recCode: "120441",
          recOrder: "6",
          recDes:
            "냄비에 준비한 양념장을 넣어 고등어가 잘 익을 때 까지 끓여준다.",
          proUrl: " ",
          proTip: " ",
        },
        {
          recProSeq: 55,
          recCode: "120441",
          recOrder: "7",
          recDes: "홍고추와 청양고추를 마지막에 넣어 한 번 더 끓여준다.",
          proUrl: "http://file.okdab.com/recipe/148222411420700033.jpg",
          proTip: " ",
        },
        {
          recProSeq: 56,
          recCode: "120441",
          recOrder: "4",
          recDes: "육수에 손질한 고등어를 넣어 끓여준다.",
          proUrl: "http://file.okdab.com/recipe/148222411420000031.jpg",
          proTip: " ",
        },
        {
          recProSeq: 57,
          recCode: "120441",
          recOrder: "3",
          recDes: "육수가 끓으면 고추장과 된장으로 밑간을 한다.",
          proUrl: "http://file.okdab.com/recipe/148222411419600030.jpg",
          proTip: "다시마와 다시멸치는 건져낸다.",
        },
        {
          recProSeq: 58,
          recCode: "120441",
          recOrder: "1",
          recDes:
            "간장, 다진마늘, 고춧가루, 설탕, 들기름을 잘 섞어 양념장을 만든다.",
          proUrl: "http://file.okdab.com/recipe/148222411418900028.jpg",
          proTip: " ",
        },
      ],
    },
    {
      recSeq: 9,
      recName: "나물 월남쌈",
      recStep: null,
      recCost: null,
      recCode: "120419",
      recSummary:
        "명절을 보내고 남은 나물로 알뜰하고 맛이게 만들어 먹는 나물 월남쌈!",
      cateCode: "3020009",
      cateFrac: "퓨전",
      foodCode: "3010007",
      foodFrac: "나물/생채/샐러드",
      cookingTime: "30분",
      recCalorie: "0Kcal",
      recAmount: "2인분",
      recLevel: "보통",
      recIngFrac: " ",
      recPrice: 9000,
      recImg: "http://file.okdab.com/recipe/148066903468800139.jpg",
      reviews: [],
      recipeIngredientList: [
        {
          recIngSeq: 1077,
          recName: "나물 월남쌈",
          ingName: "고사리",
          ingAmount: "50g",
          ingType: "주재료",
        },
        {
          recIngSeq: 1078,
          recName: "나물 월남쌈",
          ingName: "고추",
          ingAmount: "1개",
          ingType: "양념",
        },
        {
          recIngSeq: 1079,
          recName: "나물 월남쌈",
          ingName: "도라지",
          ingAmount: "50g",
          ingType: "주재료",
        },
        {
          recIngSeq: 1080,
          recName: "나물 월남쌈",
          ingName: "라이스페이퍼",
          ingAmount: "10장",
          ingType: "주재료",
        },
        {
          recIngSeq: 1081,
          recName: "나물 월남쌈",
          ingName: "매실액",
          ingAmount: "3T",
          ingType: "양념",
        },
        {
          recIngSeq: 1082,
          recName: "나물 월남쌈",
          ingName: "무채",
          ingAmount: "50g",
          ingType: "주재료",
        },
        {
          recIngSeq: 1083,
          recName: "나물 월남쌈",
          ingName: "시금치",
          ingAmount: "50g",
          ingType: "주재료",
        },
        {
          recIngSeq: 1084,
          recName: "나물 월남쌈",
          ingName: "연어살",
          ingAmount: "200g",
          ingType: "주재료",
        },
        {
          recIngSeq: 1085,
          recName: "나물 월남쌈",
          ingName: "참기름",
          ingAmount: "2T",
          ingType: "양념",
        },
        {
          recIngSeq: 1086,
          recName: "나물 월남쌈",
          ingName: "콩나물",
          ingAmount: "50g",
          ingType: "주재료",
        },
        {
          recIngSeq: 1087,
          recName: "나물 월남쌈",
          ingName: "통깨",
          ingAmount: "약간",
          ingType: "양념",
        },
      ],
      recipeProcessList: [
        {
          recProSeq: 59,
          recCode: "120419",
          recOrder: "2",
          recDes: "시금치는 끓는 물에 살짝 데친 후 물기를 빼준다.",
          proUrl: " ",
          proTip: " ",
        },
        {
          recProSeq: 60,
          recCode: "120419",
          recOrder: "1",
          recDes:
            "참기름과 매실액에 다진 고추와 깨를 넣어 잘 섞어 소스를 만들어 준다.",
          proUrl: "http://file.okdab.com/recipe/148066903469100140.jpg",
          proTip: " ",
        },
        {
          recProSeq: 61,
          recCode: "120419",
          recOrder: "3",
          recDes:
            "고사리는 물러질 때까지 삶은 후, 깨끗하게 헹궈 물기를 빼 참기름과 소금으로 간을 하고 팬에 볶아준다.",
          proUrl: " ",
          proTip: " ",
        },
        {
          recProSeq: 62,
          recCode: "120419",
          recOrder: "10",
          recDes: "접시에 담아 준비한 소스와 함께 먹는다.",
          proUrl: " ",
          proTip: " ",
        },
        {
          recProSeq: 63,
          recCode: "120419",
          recOrder: "4",
          recDes:
            "콩나물은 깨끗하게 씻을 후 끓는 물에 넣고 뚜껑을 닫고 익혀 물기를 빼준다.",
          proUrl: " ",
          proTip: " ",
        },
        {
          recProSeq: 64,
          recCode: "120419",
          recOrder: "8",
          recDes: "따듯한 물에 라이스페이퍼를 1~2초간 담군 후 접시에 깔아준다.",
          proUrl: "http://file.okdab.com/recipe/148066903470400144.jpg",
          proTip: " ",
        },
        {
          recProSeq: 65,
          recCode: "120419",
          recOrder: "7",
          recDes: "라이스페이퍼는 말기 좋게 사각형으로 잘라준다.",
          proUrl: "http://file.okdab.com/recipe/148066903470100143.jpg",
          proTip: " ",
        },
        {
          recProSeq: 66,
          recCode: "120419",
          recOrder: "6",
          recDes: "팬에 연어살을 올려 앞뒤로 구워준다.",
          proUrl: "http://file.okdab.com/recipe/148066903469800142.jpg",
          proTip: "연어살 대신 닭가슴살",
        },
        {
          recProSeq: 67,
          recCode: "120419",
          recOrder: "5",
          recDes: "무는 채 썰어 팬에 볶아준다.",
          proUrl: "http://file.okdab.com/recipe/148066903469500141.jpg",
          proTip: " ",
        },
        {
          recProSeq: 68,
          recCode: "120419",
          recOrder: "9",
          recDes: "라이스페이퍼위에 준비한 재료를 취항대로 넣고 돌돌 말아준다.",
          proUrl: "http://file.okdab.com/recipe/148066903470600145.jpg",
          proTip: " ",
        },
      ],
    },
    {
      recSeq: 10,
      recName: "애호박 구이",
      recStep: null,
      recCost: null,
      recCode: "120401",
      recSummary: "어린채소와 함께 샐러드처럼 먹을 수 있는 애호박 구이",
      cateCode: "3020001",
      cateFrac: "한식",
      foodCode: "3010007",
      foodFrac: "나물/생채/샐러드",
      cookingTime: "20분",
      recCalorie: "0Kcal",
      recAmount: "2인분",
      recLevel: "초보환영",
      recIngFrac: " ",
      recPrice: 10000,
      recImg: "http://file.okdab.com/recipe/148066561730500124.jpg",
      reviews: [],
      recipeIngredientList: [
        {
          recIngSeq: 3755,
          recName: "애호박 구이",
          ingName: "간장",
          ingAmount: "2T",
          ingType: "양념",
        },
        {
          recIngSeq: 3756,
          recName: "애호박 구이",
          ingName: "다진마늘",
          ingAmount: "0.5T",
          ingType: "양념",
        },
        {
          recIngSeq: 3757,
          recName: "애호박 구이",
          ingName: "대파",
          ingAmount: "1/2대",
          ingType: "양념",
        },
        {
          recIngSeq: 3758,
          recName: "애호박 구이",
          ingName: "맛술",
          ingAmount: "2T",
          ingType: "양념",
        },
        {
          recIngSeq: 3759,
          recName: "애호박 구이",
          ingName: "부침유",
          ingAmount: "약간",
          ingType: "주재료",
        },
        {
          recIngSeq: 3760,
          recName: "애호박 구이",
          ingName: "식초",
          ingAmount: "0.5T",
          ingType: "양념",
        },
        {
          recIngSeq: 3761,
          recName: "애호박 구이",
          ingName: "애호박",
          ingAmount: "1개",
          ingType: "주재료",
        },
        {
          recIngSeq: 3762,
          recName: "애호박 구이",
          ingName: "어린잎채소",
          ingAmount: "100g",
          ingType: "주재료",
        },
        {
          recIngSeq: 3763,
          recName: "애호박 구이",
          ingName: "올리브유",
          ingAmount: "1T",
          ingType: "양념",
        },
        {
          recIngSeq: 3764,
          recName: "애호박 구이",
          ingName: "참기름",
          ingAmount: "약간",
          ingType: "양념",
        },
        {
          recIngSeq: 3765,
          recName: "애호박 구이",
          ingName: "청양고추",
          ingAmount: "1개",
          ingType: "양념",
        },
        {
          recIngSeq: 3766,
          recName: "애호박 구이",
          ingName: "통깨",
          ingAmount: "약간",
          ingType: "양념",
        },
      ],
      recipeProcessList: [
        {
          recProSeq: 69,
          recCode: "120401",
          recOrder: "2",
          recDes:
            "그릇에 간장, 맛술, 올리브유, 다진마늘과 식초, 참기름을 넣고 다진 청양고추와 다진 파를 넣어 잘 섞어준다. 참기름과 통깨는 적당히 첨가한다.",
          proUrl: "http://file.okdab.com/recipe/148066561732200126.jpg",
          proTip: "청양고추대신 후추나 고춧가루를 넣어도 좋다.",
        },
        {
          recProSeq: 70,
          recCode: "120401",
          recOrder: "5",
          recDes:
            "구워진 애호박을 접시에 둘러 담고 가운데 어린잎채소를 올려 양념장을 뿌려준다.",
          proUrl: "http://file.okdab.com/recipe/148066561733200129.jpg",
          proTip: " ",
        },
        {
          recProSeq: 71,
          recCode: "120401",
          recOrder: "1",
          recDes: "청양고추와 대파를 다진다.",
          proUrl: "http://file.okdab.com/recipe/148066561731800125.jpg",
          proTip: "깔끔한 양념장을 원하면 고추씨를 빼준다.",
        },
        {
          recProSeq: 72,
          recCode: "120401",
          recOrder: "3",
          recDes: "애호박은 0.5CM 정도의 두께로 썰어준다.",
          proUrl: "http://file.okdab.com/recipe/148066561732600127.jpg",
          proTip: "너무 얇거나 두꺼우면 식감이 좋지 않다.",
        },
        {
          recProSeq: 73,
          recCode: "120401",
          recOrder: "4",
          recDes: "달궈진 팬에 기름을 두르고 썰어둔 애호박을 올려 구워준다.",
          proUrl: "http://file.okdab.com/recipe/148066561732900128.jpg",
          proTip: "그릴팬에 구우면 그릴자국이 나 먹음직스러워진다.",
        },
      ],
    },
  ],
  selectedRecipe: {
    recSeq: 1,
    recName: "콩비지동그랑땡",
    recStep: null,
    recCost: null,
    recCode: "195453",
    recSummary: "두부대신 콩비지를 넣어 만든 동그랑땡 맛도 좋아요!",
    cateCode: "3020001",
    cateFrac: "한식",
    foodCode: "3010018",
    foodFrac: "부침",
    cookingTime: "30분",
    recCalorie: "0Kcal",
    recAmount: "3인분",
    recLevel: "보통",
    recIngFrac: " ",
    recPrice: 1000,
    recImg: "http://file.okdab.com/recipe/148299577268400131.jpg",
    reviews: [],
    recipeIngredientList: [
      {
        recIngSeq: 5327,
        recName: "콩비지동그랑땡",
        ingName: "계란",
        ingAmount: "5개",
        ingType: "주재료",
      },
      {
        recIngSeq: 5328,
        recName: "콩비지동그랑땡",
        ingName: "다진마늘",
        ingAmount: "1T",
        ingType: "주재료",
      },
      {
        recIngSeq: 5329,
        recName: "콩비지동그랑땡",
        ingName: "다짐육",
        ingAmount: "200g",
        ingType: "주재료",
      },
      {
        recIngSeq: 5330,
        recName: "콩비지동그랑땡",
        ingName: "대파",
        ingAmount: "1대",
        ingType: "주재료",
      },
      {
        recIngSeq: 5331,
        recName: "콩비지동그랑땡",
        ingName: "밀가루",
        ingAmount: "2CUP",
        ingType: "주재료",
      },
      {
        recIngSeq: 5332,
        recName: "콩비지동그랑땡",
        ingName: "배추",
        ingAmount: "2잎",
        ingType: "주재료",
      },
      {
        recIngSeq: 5333,
        recName: "콩비지동그랑땡",
        ingName: "부침가루",
        ingAmount: "1/2T",
        ingType: "주재료",
      },
      {
        recIngSeq: 5334,
        recName: "콩비지동그랑땡",
        ingName: "소금",
        ingAmount: "2t",
        ingType: "주재료",
      },
      {
        recIngSeq: 5335,
        recName: "콩비지동그랑땡",
        ingName: "전분",
        ingAmount: "1/2T",
        ingType: "주재료",
      },
      {
        recIngSeq: 5336,
        recName: "콩비지동그랑땡",
        ingName: "참기름",
        ingAmount: "1T",
        ingType: "주재료",
      },
      {
        recIngSeq: 5337,
        recName: "콩비지동그랑땡",
        ingName: "콩비지",
        ingAmount: "300g",
        ingType: "주재료",
      },
      {
        recIngSeq: 5338,
        recName: "콩비지동그랑땡",
        ingName: "호박",
        ingAmount: "1/2개",
        ingType: "주재료",
      },
      {
        recIngSeq: 5339,
        recName: "콩비지동그랑땡",
        ingName: "후추",
        ingAmount: "1/2t",
        ingType: "주재료",
      },
    ],
    recipeProcessList: [
      {
        recProSeq: 1,
        recCode: "195453",
        recOrder: "5",
        recDes:
          "모양을 낸 반죽에 밀가루를 묻히고, 계란을 푼 계란물을 묻혀준다.",
        proUrl: "http://file.okdab.com/recipe/148299577271000135.jpg",
        proTip: " ",
      },
      {
        recProSeq: 2,
        recCode: "195453",
        recOrder: "4",
        recDes: "동그랑땡 반죽을 동글납작하게 모양을 잡아준다.",
        proUrl: "http://file.okdab.com/recipe/148299577270600134.jpg",
        proTip: " ",
      },
      {
        recProSeq: 3,
        recCode: "195453",
        recOrder: "3",
        recDes: "부침가루와 전분을 넣고 계란 1개를 넣어 반죽하듯 잘 섞어준다.",
        proUrl: "http://file.okdab.com/recipe/148299577270200133.jpg",
        proTip: " ",
      },
      {
        recProSeq: 4,
        recCode: "195453",
        recOrder: "2",
        recDes:
          "볼에 콩비지와 고기, 다진 채소, 다진마늘, 후추, 소금, 참기름을 넣어준다.",
        proUrl: "http://file.okdab.com/recipe/148299577269600132.jpg",
        proTip: " ",
      },
      {
        recProSeq: 5,
        recCode: "195453",
        recOrder: "1",
        recDes: "대파, 호박, 배추는 작게 다져준다.",
        proUrl: " ",
        proTip: " ",
      },
      {
        recProSeq: 6,
        recCode: "195453",
        recOrder: "6",
        recDes:
          "달궈진 팬에 기름을 두르고 옷을 계란물옷을 입힌 동그랑땡을 노릇하게 익혀준다.",
        proUrl: "http://file.okdab.com/recipe/148299577271500136.jpg",
        proTip: " ",
      },
    ],
  },
};

const recipeSlice = createSlice({
  name: "recipe",
  initialState,
  reducers: {
    setRecipes(state, action) {
      console.log(action.payload);
      state.recipes = action.payload;
    },
    setSelectedRecipe(state, action) {
      for (let i = 0; i < state.recipes.length; i++) {
        if (state.recipes[i].recSeq == action.payload) {
          state.selectedRecipe = state.recipes[i];
        }
      }
    },
  },
});
export const { setRecipes, setSelectedRecipe } = recipeSlice.actions;
export default recipeSlice.reducer;
